# Generated by Django 5.2 on 2025-05-10 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('Nebulosa', 'nebulosa'), ('Estrela', 'estrela'), ('Galáxia', 'galaxia'), ('Planeta', 'planeta')], default=''),
        ),
    ]
